from tkinter import *
from os import *
win = Tk()
win.title("TIC TAC TOE")
win.geometry("350x350")
win.configure(background = "blue")
def twoplay():
    system("python twoplayer.py")
def oneplay():
    system("python singleplayer.py")
heading = Label(win,text="TIC-TAC-TOE GAME",fg="white",bg="blue",height=2,width=20,font=("TimesRoman",12,'bold'))
player = Label(win,text="PLAYER 1",fg="white",bg="blue",height=2,width=20,font=("TimesRoman",12,'bold'))
pl = Button(win,text="2 PLAYERS",fg="white",bg="blue",height=2,width=10,font=("TimesRoman",12,'bold') ,command=twoplay)
p2 = Button(win,text="1 PLAYER",fg="white",bg="blue",height=2,width=10,font=("TimesRoman",12,'bold'),command=oneplay)
b0=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(0))
b1=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(1))
b2=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(2))
b3=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(3))
b4=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(4))
b5=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(5))
b6=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(6))
b7=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(7))
b8=Button(win,text='',fg="black",bg="grey",height=2,width=8,font=("TimesRoman",12,'bold'),command=lambda:buttonclicked(8))
winner = Label(win,text="",fg="white",bg="blue",height=2,width=20,font=("TimesRoman",12,'bold'))

#player.place(x=150,y=300)
heading.place(x=80,y=10)
pl.place(x=40,y=50)
p2.place(x=200,y=50)
b0.place(x=40,y=100)
b1.place(x=130,y=100)
b4.place(x=130,y=150)
b7.place(x=130,y=200)
b3.place(x=40,y=150)
b2.place(x=220,y=100)
b5.place(x=220,y=150)
b8.place(x=220,y=200)
b6.place(x=40,y=200)
winner.place(x=40,y=250)
win.mainloop()
